apiVersion: v1
kind: Service
metadata:
  name: picalc-mpmath-service
spec:
  selector:
    app: picalc-mpmath
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: picalc-mpmath
spec:
  selector:
    matchLabels:
      app: picalc-mpmath
  replicas: 4
  template:
    metadata:
      labels:
        app: picalc-mpmath
    spec:
      containers:
      - name: picalc-mpmath
        image: picalc-mpmath:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000